name: Publish NPM Package

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "template/**"
      - "tsconfig.json"
      - "package.json"
      - "README.md"

# Add permissions needed for pushing changes back to the repository
permissions:
  contents: write # Required for pushing commits and tags

jobs:
  check-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper diff analysis
          # Add token to allow pushing back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: |
          # Basic validation test to ensure CLI can be run
          if [ -f "dist/cli.js" ]; then
            echo "Verifying CLI script is executable"
            chmod +x dist/cli.js
            
            # Check if the CLI loads without errors
            if node -e "import('./dist/cli.js').then(() => { console.log('CLI loads correctly'); process.exit(0); }).catch(e => { console.error(e); process.exit(1); })"; then
              echo "✅ CLI validation passed"
            else
              echo "❌ CLI validation failed"
              exit 1
            fi
          fi

      - name: Check for version-requiring changes
        id: check-changes
        run: |
          # Get the files changed in the last commit
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

          # Check for critical changes that require version bump
          REQUIRE_VERSION_UPDATE=false

          echo "Changed files:"
          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q "^src/"; then
            echo "Files in src/ directory were modified - version update required"
            REQUIRE_VERSION_UPDATE=true
          fi

          if echo "$CHANGED_FILES" | grep -q "^template/"; then
            echo "Files in template/ directory were modified - version update required"
            REQUIRE_VERSION_UPDATE=true
          fi

          if echo "$CHANGED_FILES" | grep -q "^tsconfig.json$"; then
            echo "tsconfig.json was modified - version update required"
            REQUIRE_VERSION_UPDATE=true
          fi

          # Check for important package.json changes (except version field itself)
          if echo "$CHANGED_FILES" | grep -q "^package.json$"; then
            # Get package.json differences excluding version field
            PKG_DIFF=$(git diff HEAD^ HEAD -- package.json | grep -v '"version":')
            
            # Check if there are meaningful changes to package.json (dependencies, etc.)
            if echo "$PKG_DIFF" | grep -q '"dependencies"\|"peerDependencies"\|"bin"\|"main"\|"exports"\|"type"\|"files"'; then
              echo "Important package.json fields were modified - version update required"
              REQUIRE_VERSION_UPDATE=true
            else
              echo "Only non-critical package.json changes detected - no version update required"
            fi
          fi

          if [ "$REQUIRE_VERSION_UPDATE" = "false" ]; then
            echo "❌ No version-requiring changes detected. Exiting workflow."
            exit 1
          fi

          echo "require_version_update=$REQUIRE_VERSION_UPDATE" >> $GITHUB_OUTPUT

      - name: Determine version type from conventional commits
        id: version-type
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)

          # Check for explicit version tags
          if echo "$COMMIT_MSG" | grep -q "#major"; then
            echo "version_type=major" >> $GITHUB_OUTPUT
            echo "Using major version update from #major tag"
          elif echo "$COMMIT_MSG" | grep -q "#minor"; then
            echo "version_type=minor" >> $GITHUB_OUTPUT
            echo "Using minor version update from #minor tag"
          elif echo "$COMMIT_MSG" | grep -q "#patch"; then
            echo "version_type=patch" >> $GITHUB_OUTPUT
            echo "Using patch version update from #patch tag"
          # Check for conventional commit format
          elif echo "$COMMIT_MSG" | grep -q "^feat!:"; then
            echo "version_type=major" >> $GITHUB_OUTPUT
            echo "Using major version update from breaking change commit"
          elif echo "$COMMIT_MSG" | grep -q "^feat:"; then
            echo "version_type=minor" >> $GITHUB_OUTPUT
            echo "Using minor version update from feature commit"
          elif echo "$COMMIT_MSG" | grep -q "^fix:"; then
            echo "version_type=patch" >> $GITHUB_OUTPUT
            echo "Using patch version update from fix commit"
          else
            echo "version_type=patch" >> $GITHUB_OUTPUT
            echo "Defaulting to patch version update"
          fi

      # Make sure git is clean before version update
      - name: Clean git state
        run: |
          git status
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          # Stash any changes that might be causing the "not clean" state
          git stash -u || true

      - name: Update package version
        id: update-version
        run: |
          VERSION_TYPE="${{ steps.version-type.outputs.version_type }}"
          echo "Updating version: $VERSION_TYPE"
          # Use --no-git-tag-version to handle git operations manually
          npm --no-git-tag-version version $VERSION_TYPE

          # Use a method that works with both ESM and CommonJS
          NEW_VERSION=$(node -e "console.log(JSON.parse(require('fs').readFileSync('./package.json', 'utf8')).version)")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

          # Commit and tag manually
          git add package.json package-lock.json
          git commit -m "Bump version to $NEW_VERSION [skip ci]"
          git tag -a "v$NEW_VERSION" -m "Version $NEW_VERSION"

          # Push changes and tags
          git push --follow-tags

          echo "Updated to version $NEW_VERSION"

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Merge main into develop
        if: success()
        run: |
          git fetch origin develop
          git checkout develop
          git merge origin/main --no-edit
          git push origin develop
          echo "Merged main into develop branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create notification for successful publish
        if: success()
        run: |
          echo "✅ Published nextjs-starter-pack v${{ steps.update-version.outputs.new_version }} to npm"
