name: Update Dependencies

on:
  schedule:
    - cron: "0 0 1 * *" # First of every month at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script in isolated env
        run: |
          mkdir temp-env
          cd temp-env
          npm init -y
          npm install fs-extra node-fetch
          cp ../.github/scripts/update-deps.js .
          node update-deps.js

      - name: Authenticate using GitHub App
        id: auth
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Create or update PR to develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.auth.outputs.token }}
          branch: chore/update-dependencies
          base: develop
          title: "chore: update dependencies.json to latest versions"
          body: "This PR automatically updates dependencies.json to the latest versions."
          commit-message: "chore: update dependencies.json to latest versions"
          author: GitHub Actions <github-actions@github.com>
